version: '3.8'
services:
  movies-nestjs:
    container_name: challenge-code-meegu
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/home/api
      # - /home/api/node_modules
    env_file:
    - .env
    command: yarn start:dev
    ports:
      - 8080:8080
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:latest
    container_name: meegu-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
    volumes:
      - ./.mysql/data:/var/lib/mysql
